/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;

/**
 *
 * @author MesutKutlu
 */
public class mahkumDetails extends javax.swing.JFrame {
    boolean edit=false; 
    Integer ssn,hucre_no ;
    String isim,soyisim,blok,hucre_tipi,giris_tarihi,cikis_tarihi;
    
    /**
     * Creates new form mahkumDetails
     */
    public mahkumDetails() {
        initComponents();
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("images.jpg"))); // NOI18N

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 350));
        getContentPane().setLayout(null);

        jLabel1.setText("İsim:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(143, 18, 51, 20);

        jLabel2.setText("Soyisim:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(143, 50, 51, 20);

        jLabel3.setText("SSN:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(143, 82, 51, 20);

        jLabel4.setText("Blok:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(143, 104, 51, 40);

        jLabel5.setText("Hücre Tipi:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(143, 152, 51, 14);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 24, 113, 158);

        jLabel7.setText("Giriş Tarihi:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 180, 53, 20);

        jLabel8.setText("Çıkış Tarihi:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 210, 90, 20);

        jLabel9.setText("Hücre No:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 110, 60, 20);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(200, 20, 120, 20);

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(200, 50, 120, 20);

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(200, 80, 120, 20);

        jTextField4.setEditable(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(200, 110, 60, 20);

        jTextField5.setEditable(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(200, 150, 120, 20);

        jTextField6.setEditable(false);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(200, 180, 120, 20);

        jTextField7.setEditable(false);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(200, 210, 120, 20);

        jTextField8.setEditable(false);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(330, 110, 60, 20);

        jButton1.setText("Düzenle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 250, 71, 23);

        jButton2.setText("Sil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 250, 43, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(edit==false){
            jTextField1.setEditable(true);
            jTextField2.setEditable(true);
            jTextField3.setEditable(true);
            jTextField4.setEditable(true);
            jTextField5.setEditable(true);
            jTextField6.setEditable(true);
            jTextField7.setEditable(true);
            jTextField8.setEditable(true);
            jButton1.setText("Kaydet");
            edit = true;
        }
        else{
            mahkum yeni = new mahkum();
            yeni.edit(this.ssn,this.isim,this.soyisim,this.blok,this.hucre_tipi,this.hucre_no,this.giris_tarihi,this.cikis_tarihi,
                   Integer.valueOf(jTextField3.getText()), jTextField1.getText(),jTextField2.getText(),jTextField4.getText(),
                   jTextField5.getText(),Integer.valueOf(jTextField8.getText()),jTextField6.getText(),jTextField7.getText());
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
            jTextField3.setEditable(false);
            jTextField4.setEditable(false);
            jTextField5.setEditable(false);
            jTextField6.setEditable(false);
            jButton1.setText("Düzenle");
            edit = false;
        }       
    }//GEN-LAST:event_jButton1ActionPerformed
    void infos(Integer ssn, String isim, String soyisim, String blok, String hucre_tipi, Integer hucre_no, String giris_tarihi, String cikis_tarihi) {
        this.ssn = ssn;
        this.isim =isim;
        this.soyisim = soyisim;
        this.blok = blok;
        this.hucre_tipi = hucre_tipi;
        this.hucre_no = hucre_no;
        this.giris_tarihi =  giris_tarihi;
        this.cikis_tarihi = cikis_tarihi;
        jTextField1.setText(isim);
        jTextField2.setText(soyisim);
        jTextField3.setText(ssn.toString());
        jTextField4.setText(blok);
        jTextField5.setText(hucre_tipi);
        jTextField6.setText(giris_tarihi);
        jTextField7.setText(cikis_tarihi);
        jTextField8.setText(hucre_no.toString());
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    mahkum yeni = new mahkum();
        int value = JOptionPane.showConfirmDialog(null, "Silmek istediğinize emin misiniz?");
        if(value==0){
            yeni.sil(Integer.valueOf(jTextField1.getText()), jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),
                   jTextField5.getText(),Integer.valueOf(jTextField6.getText()),jTextField7.getText(),jTextField8.getText());
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mahkumDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mahkumDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mahkumDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mahkumDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mahkumDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables


}
